<div class="row">
	<div class="header-link col-lg-7 col-md-7 col-sm-7 col-xs-7">
		<table class="header-table">
			<tr>
				<td class="header-1"><a href="#"><?= /* @escapeNotVerified */ __('Help') ?></a></td>
				<td class="header-2"><a href="#"><?= /* @escapeNotVerified */ __('Contact') ?></a></td>
				<td class="header-3"><a href="#"><?= /* @escapeNotVerified */ __('Delivery Information') ?></a></td>
			</tr>
		</table>
	</div>
    <div class="call col-md-5 col-lg-5 col-sm-5 col-xs-5">
        <span><img class="header-call" src="<?php echo $this->getViewFileUrl("images/header-call.png");?>"/><?= /* @escapeNotVerified */ __('Call us : 032 2352 782') ?></span>
    </div>
</div>